/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#323538",
        "secondary-fixed": "#ffdada",
        "outline": "#869488",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2e7",
        "surface-variant": "#323538",
        "secondary-fixed-dim": "#ffb3b5",
        "on-primary": "#00391f",
        "error-container": "#93000a",
        "on-secondary": "#680019",
        "on-primary-container": "#004728",
        "on-tertiary-container": "#4300b8",
        "surface-container-lowest": "#0b0e11",
        "on-background": "#e1e2e7",
        "on-primary-fixed-variant": "#00522f",
        "inverse-on-surface": "#2e3134",
        "on-tertiary": "#360096",
        "on-tertiary-fixed-variant": "#4d17c5",
        "on-secondary-fixed-variant": "#920027",
        "on-surface": "#e1e2e7",
        "tertiary-fixed-dim": "#ccbdff",
        "surface-container-low": "#191c1f",
        "surface-container": "#1d2023",
        "on-secondary-container": "#ffcccd",
        "on-primary-fixed": "#002110",
        "outline-variant": "#3c4a40",
        "background": "#111417",
        "primary": "#44e092",
        "surface-container-high": "#272a2e",
        "surface-tint": "#44e092",
        "surface-dim": "#111417",
        "on-secondary-fixed": "#40000c",
        "secondary": "#ffb3b5",
        "primary-fixed-dim": "#44e092",
        "on-surface-variant": "#bbcabd",
        "tertiary-fixed": "#e7deff",
        "secondary-container": "#be0336",
        "tertiary": "#ccbdff",
        "surface-bright": "#37393d",
        "surface": "#111417",
        "inverse-primary": "#006d41",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "tertiary-container": "#af99ff",
        "primary-fixed": "#66fdac",
        "primary-container": "#00c076",
        "on-tertiary-fixed": "#1f005f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "4px",
        "gutter": "16px",
        "unit": "4px",
        "margin": "24px",
        "xl": "32px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "data-md": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
